/*
 * ViewerOptions.h
 *
 *  Created on: Dec 20, 2011
 *      Author: jim
 */

#ifndef VIEWEROPTIONS_H_
#define VIEWEROPTIONS_H_

enum OpMode {
	OPMODE_EXTRACT_AND_VIEW_SURFACE,
	OPMODE_EXTRACT_BATCH,
	OPMODE_VIEW_POLYDATA,
	OPMODE_VIEW_VOLUME,
	OPMODE_PLOT_VIEW_TRIANGLE_AVERAGES,
	OPMODE_PLOT_VIEW_SURFACE_AREAS,
	OPMODE_PLOTS_TRIANGLE_AVERAGES,
	OPMODE_PLOTS_BATCH_TRIANGLE_AVERAGES,
	OPMODE_PLOTS_BATCH_SURFACE_AREAS };

struct ViewerOptions
{
	OpMode mode;
	char *outDir;
};


#endif /* VIEWEROPTIONS_H_ */
